service: api
app: hellosigndashboardapi
org: yotavm

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: users/create
  getList:
    handler: functions/getSignrequestsList.getList
    events:
      - http:
          method: get
          path: signRequests
