service: api
app: hellosigndashboardapi
org: yotavm
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: users/create