service: api
app: hellosigndashboardapi
org: yotavm

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    HELLOSIGN_API_KEY: ${ssm:/HELLOSIGN_API_KEY~true}
    HELLOSIGN_APP_CLIENT_ID: ${ssm:/HELLOSIGN_APP_CLIENT_ID~true}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  getList:
    handler: functions/signRequests.getList
    events:
      - http:
          method: get
          path: signRequests

custom:
  webpack:
    webpackConfig: "webpack.config.js" # name of webpack configuration file
    includeModules: true # add excluded modules to the bundle
    packager: "npm" # package manager we use
