service: api
app: hellosigndashboardapi
org: yotavm

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  getList:
    handler: functions/signRequests.getList
    environment:

    events:
      - http:
          method: get
          path: signRequests

custom:
  webpack:
    webpackConfig: "webpack.config.js" # name of webpack configuration file
    includeModules: true # add excluded modules to the bundle
    packager: "npm" # package manager we use
